name: Deploy on Weekend

on:
  schedule:
    - cron: '0 20 * * 5'
    - cron: '0 20 * * 6'
    - cron: '0 20 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        run: vercel deploy --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
