name: Sync Fork v1.2.1

on:
  schedule:
    - cron: '* * * * *' # every 5 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.SECRET_WORKFLOW }}
          owner: Yagasaki7K
          base: main
          head: main
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
